# Generated by Django 2.1.2 on 2018-11-01 15:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('description', models.TextField()),
                ('shops', models.TextField()),
                ('open_food_fact_url', models.URLField()),
                ('personal_url', models.URLField()),
                ('photo_url', models.URLField()),
                ('nutriscore', models.CharField(max_length=1)),
                ('categories', models.ManyToManyField(to='products.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Substitute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_product', models.ForeignKey(on_delete=True, related_name='base_product', to='products.Product')),
                ('substituted', models.ForeignKey(on_delete=True, related_name='substituted', to='products.Product')),
                ('user', models.ForeignKey(on_delete=True, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
