# Generated by Django 2.1.3 on 2018-11-01 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20181101_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='open_food_fact_url',
            field=models.URLField(max_length=250),
        ),
        migrations.AlterField(
            model_name='product',
            name='personal_url',
            field=models.URLField(max_length=250),
        ),
        migrations.AlterField(
            model_name='product',
            name='photo_url',
            field=models.URLField(max_length=250),
        ),
    ]
