# Generated by Django 2.1.3 on 2018-11-04 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20181101_1948'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_nutrition',
            field=models.URLField(default='example.com', max_length=250),
            preserve_default=False,
        ),
    ]
