# Generated by Django 2.1.3 on 2018-11-04 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_image_nutrition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image_nutrition',
            field=models.URLField(max_length=300),
        ),
    ]
