# Generated by Django 2.1.4 on 2019-01-05 12:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20181104_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='modified_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='substitute',
            name='base_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='base_product', to='products.Product'),
        ),
        migrations.AlterField(
            model_name='substitute',
            name='substituted',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='substituted', to='products.Product'),
        ),
        migrations.AlterField(
            model_name='substitute',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
