# Generated by Django 2.1.7 on 2019-02-27 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_remove_profile_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='news_letter',
            field=models.BooleanField(default=False),
        ),
    ]
