# Generated by Django 2.1.7 on 2019-02-28 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_profile_news_letter'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.FileField(blank=True, upload_to='avatars/'),
        ),
        migrations.AddField(
            model_name='profile',
            name='description',
            field=models.CharField(default='', max_length=10000),
        ),
    ]
